# Generated by Django 4.2.7 on 2023-11-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Popular_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=100)),
                ('students', models.CharField(max_length=50)),
                ('lessons', models.CharField(max_length=50)),
                ('fees', models.CharField(max_length=50)),
            ],
        ),
    ]
