# Generated by Django 4.2.7 on 2023-11-23 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_events"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.DeleteModel(
            name="Email",
        ),
    ]
