# Generated by Django 4.2.7 on 2023-11-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="popular_courses",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
